### ISSUE TITLE
Using rejson as a module

### ISSUE THREAD

**Issue by mschipperheyn** [dokku/dokku-redis#107]
ReJSON is a Redis module that allows you to read and write JSON content to Redis. I am wondering if it would be possible and if so how, to use this module with dokku-redis?

**Comment by josegonzalez** [comment]
You would need to switch the image in use. From our docs:

```
# it *must* be compatible with the
# official redis image
export REDIS_IMAGE="redis"
export REDIS_IMAGE_VERSION="2.8.21"
dokku redis:create lolipop
```

**Comment by josegonzalez** [comment]
Note that this is outside of the official redis setup, so we won't be providing much support, but you should be able to build a new image based on the official one and go from there :)

Join us on slack with any questions and we should be able to help you out.

**Comment by mschipperheyn** [comment]
So, for those stumbling upon this: this is the way to get it working:
Thanks @josegonzalez for the help!

- Copy the redis.conf https://raw.githubusercontent.com/antirez/redis/4.0.11/redis.conf (or whatever version is actual)
- Add `loadmodule /usr/lib/redis/modules/rejson.so` to it
- Place the file on the dokku server, e.g. /data/redis.conf
```
sudo dokku plugin:install https://github.com/dokku/dokku-redis.git redis
export REDIS_IMAGE="redislabs/rejson"
export REDIS_IMAGE_VERSION="latest"
export REDIS_CONFIG_PATH="/data/redis.conf"
dokku redis:create redis-rejson
dokku redis:link redis-rejson your_app_name
```

**Comment by brainomite** [comment]
Old issue: I wanted to document how I got redisJSON working in 2024 using `redis-stack`

```bash
### change appname and dbname to your setup
export appname="test" &&
export dbname="test-db" &&

export REDIS_IMAGE="redis/redis-stack" &&
### locate the correct redis version from the docker registry - "latest" doesn't work
export REDIS_IMAGE_VERSION="7.4.0-v0" &&

dokku redis:create $dbname &&
### enable redisJSON
echo loadmodule /opt/redis-stack/lib/rejson.so>>/var/lib/dokku/services/redis/"$dbname"/config/redis.conf &&
### restart to take effect
dokku redis:restart $dbname
dokku redis:link $dbname $appname
```
