### ISSUE TITLE
Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for [::1]:6379)

### ISSUE THREAD

**Issue by matissg** [dokku/dokku-redis#114]
I'm stuck with this error. **In production** when I do image upload (Rails Active Storage, direct_upload) I get this fatal error:
`Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for [::1]:6379)`

I thought it is something related to Puma as [in this issue](https://github.com/puma/puma/issues/1062), but no - I tried to changed as suggested, but no luck.

`sudo nano /etc/hosts` gives me this:
```
127.0.1.1 dokku-own-apps dokku-own-apps
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```
My dokku redis info:
```
root@dokku-own-apps:~# dokku redis:info dokku-own-apps
=====> Container Information
       Config dir:          /var/lib/dokku/services/redis/dokku-own-apps/config
       Data dir:            /var/lib/dokku/services/redis/dokku-own-apps/data
       Dsn:                 redis://dokku-own-apps:[some random id]@dokku-redis-dokku-own-apps:6379
       Exposed ports:       -
       Id:                  [some random id]
       Internal ip:         172.17.0.4
       Links:               myappname
       Service root:        /var/lib/dokku/services/redis/dokku-own-apps
       Status:              running
       Version:             redis:4.0.11
```
My dokku redis list:
```
root@dokku-own-apps:~# dokku redis:list
NAME            VERSION       STATUS   EXPOSED PORTS  LINKS
dokku-own-apps  redis:4.0.11  running  -              myappname
```

**How can I fix this, please?**
Everything works just fine in development on my local machine.

**Comment by matissg** [comment]
@josegonzalez  I'm using Dokku for my DigitalOcean droplet and it looks like this:
```
2018-10-28T19:30:08.620980344Z app[web.1]: D, [2018-10-28T19:30:08.620845 #8] DEBUG -- : [2b0d53ae-33b4-4d20-967b-025fe9ee375d]   ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "image"], ["record_type", "Medium::Medium"], ["record_id", 6], ["blob_id", 34], ["created_at", "2018-10-28 19:30:08.619763"]]
2018-10-28T19:30:08.623729115Z app[web.1]: D, [2018-10-28T19:30:08.623536 #8] DEBUG -- : [2b0d53ae-33b4-4d20-967b-025fe9ee375d]    (0.4ms)  ROLLBACK
2018-10-28T19:30:08.624458248Z app[web.1]: I, [2018-10-28T19:30:08.624358 #8]  INFO -- : [2b0d53ae-33b4-4d20-967b-025fe9ee375d] Completed 500 Internal Server Error in 20ms (ActiveRecord: 4.0ms)
2018-10-28T19:30:08.630157879Z app[web.1]: F, [2018-10-28T19:30:08.629906 #8] FATAL -- : [2b0d53ae-33b4-4d20-967b-025fe9ee375d]
2018-10-28T19:30:08.630369597Z app[web.1]: F, [2018-10-28T19:30:08.630254 #8] FATAL -- : [2b0d53ae-33b4-4d20-967b-025fe9ee375d] Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for [::1]:6379):
```
No errors when I upload image locally.

**Comment by josegonzalez** [comment]
Is your application respecting `REDIS_URL` when connecting to redis? Sounds like maybe it isn't.

**Comment by matissg** [comment]
@josegonzalez I don't think so. At least I'm not using `REDIS_URL` in my `production.rb`
I tried to use `config.cache_store = :redis_cache_store, {url: "redis://dokku-own-apps:[some random id]@dokku-redis-dokku-own-apps:6379"}` however it didn't help - nothing changed as the errors stayed.
In development I just launch `redis-server` and it works.

**Comment by josegonzalez** [comment]
That just says it can't talk to redis, but without a longer stacktrace, I can't really dig into this - it also sounds like an app error.

Can you connect to the redis instance and verify its working? If so, then I'm not sure what else to dig into.

**Comment by matissg** [comment]
@josegonzalez  Thank you, looks like there is some connection error since I get this in my console:
```
root@dokku-own-apps:~# redis-cli ping
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
Could it be something related to firewall or similar?

**Comment by josegonzalez** [comment]
The redis instance doesn't run directly on the host, it runs in a container. It sounds like your application isn't respecting your redis configuration, and isn't talking to the right hostname.

**Comment by matissg** [comment]
@josegonzalez From `dokku redis:info dokku-own-apps` what hostname I should be pointing my app, please?

**Comment by josegonzalez** [comment]
You should not be hardcoding the value, and instead respecting the `REDIS_URL` env var.

**Comment by matissg** [comment]
@josegonzalez In my console I can do:
```
root@dokku-own-apps:~# dokku run myappname rails c
Loading production environment (Rails 5.2.1)
irb(main):001:0> r = Redis.new
=> #<Redis client v4.0.2 for redis://dokku-redis-dokku-own-apps:6379/0>
irb(main):002:0> r.ping
=> "PONG"
```
I believe this means Redis is working, it's just my app is not connected properly.

In my Rails 5 app in `app\config\redis.yml` I have:
```
default: &default
  url: redis://localhost:6379
  db: 0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: redis://dokku-redis-dokku-own-apps:6379/0
```
but this is not working. Do you have some idea, what am I doing wrong here? I'm trying to follow [this config suggestion](https://gist.github.com/pubis/1459506/4b71e9c50c9d4425acfdf2fcbd1fd9fa075782ad#gistcomment-1775155).

**Comment by josegonzalez** [comment]
You need to also have the password. We set a password in all redis services, and if you don't use it, your connection will fail.

**Comment by matissg** [comment]
@josegonzalez  My bad - I missed Rails ActiveStorage used Sidekiq in background and there my `config\initializers\sidekiq.rb` missed `ENV["REDIS_URL"]`. 
So it has to look like this:
```
Sidekiq.configure_server do |config|
  config.redis = { url: (ENV["REDIS_URL"] || 'redis://localhost:6379/0') }
end

Sidekiq.configure_client do |config|
  config.redis = { url: (ENV["REDIS_URL"] || 'redis://localhost:6379/0') }
end
```
I anyone from Rails community runs into same situation, it could be probably due to this. Just change `sidekiq.rb` to respect `ENV["REDIS_URL"]` and it should work. No other changes apart from what is defined here in `dokku-redis` setup.

Thank you for patience + so far Dokku looks really nice. Thank you!

**Comment by josegonzalez** [comment]
No problem! Glad to hear it wasn't us :)
