### ISSUE TITLE
Restoring from AWS backup

### ISSUE THREAD

**Issue by peerbolte** [dokku/dokku-redis#120]
I'm having trouble restoring an export file from AWS. I'm running a backup and storing it to AWS S3.

The format of the file that is stored on S3: 
`mongo-backend-2018-05-15-09-55-05.tgz`

After downloading the file to the server I run
`dokku mongo:import db-test < mongo-backend-2018-05-15-09-55-05.tgz`
I get the following error: `Failed: stream or file does not appear to be a mongodump archive`

I tried running the following after that:
`tar xvf mongo-backend-2018-05-15-09-55-05.tgz`
The file is extracted to backup/export 

If I try to import that file:
`dokku mongo:import db-test < export`
I get the following error: `Failed: gzip: invalid header read unix @->/var/run/docker.sock: read: connection reset by peer`

When I run tar on export I do get a file structure with the collections in json format. I am not able to import this however. Am I missing something here?

**Comment by josegonzalez** [comment]
Backup restoration was documented in the following commits (and done so for all other plugins as well):

- https://github.com/dokku/dokku-redis/commit/17a640e76498555b7750fc6257f4c0d0d2d96a01
- https://github.com/dokku/dokku-redis/commit/3aed82c9d723c62506fc45bdd5162dd321b98c7f

You'll need to download your backup (`curl` or `wget` both work and should be installed).
