### ISSUE TITLE
Unable to use default or generated URL alias

### ISSUE THREAD

**Issue by znz** [dokku/dokku-redis#121]
If `DOKKU_POSTGRES_YELLOW_URL` exists, `dokku postgres:link` failed.

I think https://github.com/dokku/dokku-postgres/blob/f30db928fb8a608327118ad2e0443594c8cd0bdf/common-functions#L111-L117 do finally unset ALIAS if YELLOW alias exists.

**Comment by josegonzalez** [comment]
Sorry for taking a while to get back to this.

Is the issue here that you already have every "color" attached to a the server, and therefore have run out of color aliases?

**Comment by mehrdadn** [comment]
Hi Jose, it seems to me [the fix](/dokku/dokku-redis/commit/e3b9237e593d26a02b377463a26e246f1e19c3dd) in #64 makes the loop potentially buggy. Right now the loop goes through _all_ colors, and `ALIAS` can only ever be `YELLOW` or an empty string once the loop ends. It doesn't seem like it can ever be any other color. Is this correct? It seems like a `break` might be missing in the loop.

**Comment by josegonzalez** [comment]
Yeah I'm aware of the issue.

I recently took a new position where I'll be concentrating on Dokku and the ecosystem around it, so I should be able to pick this - and other datastore issues - up Real Soon™.

**Comment by ppawlak** [comment]
Hello,

I had this error message when i tried to link a second app to a postgres database : 

`
dokku@dokku:~$ dokku postgres:link my_database another-app
Unable to use default or generated URL alias
`


Any idea how to fix?

**Comment by josegonzalez** [comment]
@ppawlak What version of the dokku-redis plugin are you using? Also, what is the output of:

```shell
dokku --trace postgres:link my_database another-app
```

**Comment by ppawlak** [comment]
@josegonzalez 
My  redis plugin is version 1.6.1. How is it related to this issue? (I want to link a postgres database)

I've attached my trace log with passwords obfuscated, app names replaced by _app1_, _app2_ , _app3_ and databases names replaced by _app1_database_ , _app2_databse_, _app3_database_

[trace.txt](https://github.com/dokku/dokku-redis/files/3666619/trace.txt)

**Comment by josegonzalez** [comment]
The version of the software you are using is always connected to any bugs that software may or may not have.

I'll take a look at your trace output tomorrow, thanks for that!

**Comment by ppawlak** [comment]
> I'll take a look at your trace output tomorrow, thanks for that!

@josegonzalez Did you have a look at it? Any idea how I can fix this and link several databases to the same app ? Thanks!

**Comment by ppawlak** [comment]
@josegonzalez I just updated dokku postgres plugin to version 1.9.1 (I was on version 1.4.12) and the problem seems to be fixed now. Sorry for the noise and thank you for your help!
