### ISSUE TITLE
Container missing after reboot

### ISSUE THREAD

**Issue by ivanmonteiro** [dokku/dokku-redis#135]
After I rebooted my Ubuntu Server, mysql databases created using dokku's mysql plugin are missing and linked apps can't start up because of this.

Output of `dokku mysql:list`

> ubuntu@ip-172-26-1-185:~$ dokku mysql:list
> NAME         VERSION       STATUS   EXPOSED PORTS  LINKS
> a69          mysql:5.7.12  missing  -              a69
> fipefuturo   mysql:5.7.12  running  -              fipefuturo
> multisitedb  mysql:5.7.12  missing  3306->23102    multisite`

**Comment by josegonzalez** [comment]
Likely something cleaned up those old containers. That said, we have issue #138 to resolve this.
