### ISSUE TITLE
Restoring From S3 Backup

### ISSUE THREAD

**Issue by archy-bold** [dokku/dokku-redis#140]
Is there a way to restore S3 backups from the CLI? Or maybe plans to implement this as a feature? Or do we need to restore manually?

**Comment by josegonzalez** [comment]
Backup restoration was documented in the following commits:

- https://github.com/dokku/dokku-redis/commit/17a640e76498555b7750fc6257f4c0d0d2d96a01
- https://github.com/dokku/dokku-redis/commit/3aed82c9d723c62506fc45bdd5162dd321b98c7f

You'll need to download your backup (`curl` or `wget` both work and should be installed).

We won't be exposing a simple command to restore the backup at this time. If someone would like to sponsor that work, I'm happy to take a look.
