### ISSUE TITLE
Issue by trying to re-expose a database [postgres]

### ISSUE THREAD

**Issue by itstheandre** [dokku/dokku-redis#153]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version before filing an issue.

## Description of problem
I was trying to unexpose my database, and then after i tried to `re expose it` and got an issue about a container already in use.

### How reproducible
After deleting said container everything was running again

### Steps to Reproduce

1. dokku postgres:expose {db-name} 5432
2. dokku postgres:unexpose {db-name}
3. dokku postgres:expose {db-name} 5432

#### Actual Results
![image](https://user-images.githubusercontent.com/51658452/94846534-97ac1080-0421-11eb-8bc9-0a3ddc2549a5.png)

#### Expected Results

-----> Service pg exposed on port(s) [container->host]: 5432->5432

The solution that @josegonzalez came up with was to run the command `docker rm -f dokku.postgres.ambassador` which was the container that was erroring out.

And from there it was working.

As per request I also added the following command `dokku --trace postgres:unexpose pg`
```
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest
+ DOKKU_IMAGE=gliderlabs/herokuish:latest
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=2803
+ DOKKU_PID=2803
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args postgres:unexpose pg
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ postgres:unexpose == \-\-\a\p\p ]]
+ [[ postgres:unexpose =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ pg == \-\-\a\p\p ]]
+ [[ pg =~ ^--.* ]]
+ next_index=3
+ [[ -z --trace ]]
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ postgres:unexpose =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ postgres:unexpose =~ ^plugin:.* ]]
+ [[ postgres:unexpose == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ postgres:unexpose == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
+ [[ -n '' ]]
+ dokku_auth postgres:unexpose pg
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=andre
+ SSH_USER=andre
+ export SSH_NAME=default
+ SSH_NAME=default
++ wc -l
++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
+ [[ 1 == 1 ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd postgres:unexpose pg
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=postgres:unexpose
+ local PLUGIN_CMD=postgres:unexpose
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/postgres
+ [[ /var/lib/dokku/plugins/available/postgres == *core-plugins* ]]
+ [[ -x /var/lib/dokku/plugins/enabled/postgres:unexpose/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/postgres:unexpose/subcommands/postgres:unexpose ]]
+ [[ -x /var/lib/dokku/plugins/enabled/postgres/subcommands/unexpose ]]
+ [[ -n unexpose ]]
+ /var/lib/dokku/plugins/enabled/postgres/subcommands/unexpose postgres:unexpose pg
+ source /var/lib/dokku/plugins/enabled/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++++ dirname /var/lib/dokku/plugins/enabled/postgres/subcommands/unexpose
+++ cd /var/lib/dokku/plugins/enabled/postgres/subcommands
+++ pwd
++ dirname /var/lib/dokku/plugins/enabled/postgres/subcommands
+ source /var/lib/dokku/plugins/enabled/postgres/functions
++++ dirname /var/lib/dokku/plugins/enabled/postgres/functions
+++ cd /var/lib/dokku/plugins/enabled/postgres
+++ pwd
++ source /var/lib/dokku/plugins/enabled/postgres/config
+++ export POSTGRES_IMAGE=postgres
+++ POSTGRES_IMAGE=postgres
+++ export POSTGRES_IMAGE_VERSION=11.6
+++ POSTGRES_IMAGE_VERSION=11.6
+++ export POSTGRES_ROOT=/var/lib/dokku/services/postgres
+++ POSTGRES_ROOT=/var/lib/dokku/services/postgres
+++ export POSTGRES_HOST_ROOT=/var/lib/dokku/services/postgres
+++ POSTGRES_HOST_ROOT=/var/lib/dokku/services/postgres
+++ PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=()
+++ export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS
+++ export PLUGIN_COMMAND_PREFIX=postgres
+++ PLUGIN_COMMAND_PREFIX=postgres
+++ export PLUGIN_CONFIG_ROOT=/var/lib/dokku/config/postgres
+++ PLUGIN_CONFIG_ROOT=/var/lib/dokku/config/postgres
+++ export PLUGIN_DATA_ROOT=/var/lib/dokku/services/postgres
+++ PLUGIN_DATA_ROOT=/var/lib/dokku/services/postgres
+++ export PLUGIN_DATA_HOST_ROOT=/var/lib/dokku/services/postgres
+++ PLUGIN_DATA_HOST_ROOT=/var/lib/dokku/services/postgres
+++ PLUGIN_DATASTORE_PORTS=(5432)
+++ export PLUGIN_DATASTORE_PORTS
+++ export PLUGIN_DATASTORE_WAIT_PORT=5432
+++ PLUGIN_DATASTORE_WAIT_PORT=5432
+++ export PLUGIN_DEFAULT_ALIAS=DATABASE
+++ PLUGIN_DEFAULT_ALIAS=DATABASE
+++ export PLUGIN_DISABLE_PULL=
+++ PLUGIN_DISABLE_PULL=
+++ export PLUGIN_DISABLE_PULL_VARIABLE=POSTGRES_DISABLE_PULL
+++ PLUGIN_DISABLE_PULL_VARIABLE=POSTGRES_DISABLE_PULL
+++ export PLUGIN_ALT_ALIAS=DOKKU_POSTGRES
+++ PLUGIN_ALT_ALIAS=DOKKU_POSTGRES
+++ export PLUGIN_IMAGE=postgres
+++ PLUGIN_IMAGE=postgres
+++ export PLUGIN_IMAGE_VERSION=11.6
+++ PLUGIN_IMAGE_VERSION=11.6
+++ export PLUGIN_SCHEME=postgres
+++ PLUGIN_SCHEME=postgres
+++ export PLUGIN_SERVICE=Postgres
+++ PLUGIN_SERVICE=Postgres
+++ export PLUGIN_VARIABLE=POSTGRES
+++ PLUGIN_VARIABLE=POSTGRES
+++ export PLUGIN_BASE_PATH=/var/lib/dokku/plugins
+++ PLUGIN_BASE_PATH=/var/lib/dokku/plugins
+++ export PLUGIN_CONFIG_SUFFIX=data
+++ PLUGIN_CONFIG_SUFFIX=data
+++ [[ -n 1 ]]
+++ export PLUGIN_BASE_PATH=/var/lib/dokku/plugins/enabled
+++ PLUGIN_BASE_PATH=/var/lib/dokku/plugins/enabled
+++ export PLUGIN_BUSYBOX_IMAGE=busybox:1.31.1-uclibc
+++ PLUGIN_BUSYBOX_IMAGE=busybox:1.31.1-uclibc
+++ export PLUGIN_AMBASSADOR_IMAGE=dokku/ambassador:0.3.3
+++ PLUGIN_AMBASSADOR_IMAGE=dokku/ambassador:0.3.3
+++ export PLUGIN_S3BACKUP_IMAGE=dokku/s3backup:0.10.3
+++ PLUGIN_S3BACKUP_IMAGE=dokku/s3backup:0.10.3
+++ export PLUGIN_WAIT_IMAGE=dokku/wait:0.4.3
+++ PLUGIN_WAIT_IMAGE=dokku/wait:0.4.3
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++++ dirname /var/lib/dokku/plugins/enabled/postgres/functions
+++ cd /var/lib/dokku/plugins/enabled/postgres
+++ pwd
++ source /var/lib/dokku/plugins/enabled/postgres/common-functions
+++++ dirname /var/lib/dokku/plugins/enabled/postgres/common-functions
++++ cd /var/lib/dokku/plugins/enabled/postgres
++++ pwd
+++ source /var/lib/dokku/plugins/enabled/postgres/config
++++ export POSTGRES_IMAGE=postgres
++++ POSTGRES_IMAGE=postgres
++++ export POSTGRES_IMAGE_VERSION=11.6
++++ POSTGRES_IMAGE_VERSION=11.6
++++ export POSTGRES_ROOT=/var/lib/dokku/services/postgres
++++ POSTGRES_ROOT=/var/lib/dokku/services/postgres
++++ export POSTGRES_HOST_ROOT=/var/lib/dokku/services/postgres
++++ POSTGRES_HOST_ROOT=/var/lib/dokku/services/postgres
++++ PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=()
++++ export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS
++++ export PLUGIN_COMMAND_PREFIX=postgres
++++ PLUGIN_COMMAND_PREFIX=postgres
++++ export PLUGIN_CONFIG_ROOT=/var/lib/dokku/config/postgres
++++ PLUGIN_CONFIG_ROOT=/var/lib/dokku/config/postgres
++++ export PLUGIN_DATA_ROOT=/var/lib/dokku/services/postgres
++++ PLUGIN_DATA_ROOT=/var/lib/dokku/services/postgres
++++ export PLUGIN_DATA_HOST_ROOT=/var/lib/dokku/services/postgres
++++ PLUGIN_DATA_HOST_ROOT=/var/lib/dokku/services/postgres
++++ PLUGIN_DATASTORE_PORTS=(5432)
++++ export PLUGIN_DATASTORE_PORTS
++++ export PLUGIN_DATASTORE_WAIT_PORT=5432
++++ PLUGIN_DATASTORE_WAIT_PORT=5432
++++ export PLUGIN_DEFAULT_ALIAS=DATABASE
++++ PLUGIN_DEFAULT_ALIAS=DATABASE
++++ export PLUGIN_DISABLE_PULL=
++++ PLUGIN_DISABLE_PULL=
++++ export PLUGIN_DISABLE_PULL_VARIABLE=POSTGRES_DISABLE_PULL
++++ PLUGIN_DISABLE_PULL_VARIABLE=POSTGRES_DISABLE_PULL
++++ export PLUGIN_ALT_ALIAS=DOKKU_POSTGRES
++++ PLUGIN_ALT_ALIAS=DOKKU_POSTGRES
++++ export PLUGIN_IMAGE=postgres
++++ PLUGIN_IMAGE=postgres
++++ export PLUGIN_IMAGE_VERSION=11.6
++++ PLUGIN_IMAGE_VERSION=11.6
++++ export PLUGIN_SCHEME=postgres
++++ PLUGIN_SCHEME=postgres
++++ export PLUGIN_SERVICE=Postgres
++++ PLUGIN_SERVICE=Postgres
++++ export PLUGIN_VARIABLE=POSTGRES
++++ PLUGIN_VARIABLE=POSTGRES
++++ export PLUGIN_BASE_PATH=/var/lib/dokku/plugins
++++ PLUGIN_BASE_PATH=/var/lib/dokku/plugins
++++ export PLUGIN_CONFIG_SUFFIX=data
++++ PLUGIN_CONFIG_SUFFIX=data
++++ [[ -n 1 ]]
++++ export PLUGIN_BASE_PATH=/var/lib/dokku/plugins/enabled
++++ PLUGIN_BASE_PATH=/var/lib/dokku/plugins/enabled
++++ export PLUGIN_BUSYBOX_IMAGE=busybox:1.31.1-uclibc
++++ PLUGIN_BUSYBOX_IMAGE=busybox:1.31.1-uclibc
++++ export PLUGIN_AMBASSADOR_IMAGE=dokku/ambassador:0.3.3
++++ PLUGIN_AMBASSADOR_IMAGE=dokku/ambassador:0.3.3
++++ export PLUGIN_S3BACKUP_IMAGE=dokku/s3backup:0.10.3
++++ PLUGIN_S3BACKUP_IMAGE=dokku/s3backup:0.10.3
++++ export PLUGIN_WAIT_IMAGE=dokku/wait:0.4.3
++++ PLUGIN_WAIT_IMAGE=dokku/wait:0.4.3
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/plugins/available/config/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++++ source /var/lib/dokku/core-plugins/available/common/functions
+++++ set -eo pipefail
+++++ [[ -n 1 ]]
+++++ set -x
++ source /var/lib/dokku/plugins/enabled/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++ [[ -f /var/lib/dokku/plugins/available/docker-options/functions ]]
++ source /var/lib/dokku/plugins/available/docker-options/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+++ AVAILABLE_PHASES=(build deploy run)
+ service-unexpose-cmd postgres:unexpose pg
+ declare 'desc=unexpose a previously exposed Postgres service'
+ argv=("$@")
+ local cmd=postgres:unexpose argv
+ [[ postgres:unexpose == \p\o\s\t\g\r\e\s\:\u\n\e\x\p\o\s\e ]]
+ shift 1
+ declare SERVICE=pg
+ [[ -z pg ]]
+ verify_service_name pg
+ declare 'desc=Verifies that a service exists'
+ declare SERVICE=pg
+ [[ -z pg ]]
+ [[ ! -d /var/lib/dokku/services/postgres/pg ]]
+ return 0
+ service_port_unexpose pg
+ declare 'desc=Wrapper for pausing exposed service ports'
+ declare SERVICE=pg
+ local SERVICE_ROOT=/var/lib/dokku/services/postgres/pg
+ local PORT_FILE=/var/lib/dokku/services/postgres/pg/PORT
+ service_port_pause pg true
+ declare 'desc=Pauses service exposure'
+ declare SERVICE=pg LOG_FAIL=true
+ local SERVICE_ROOT=/var/lib/dokku/services/postgres/pg
++ get_service_name pg
++ declare 'desc=Retrieves a docker service label'
++ declare SERVICE=pg
++ echo dokku.postgres.pg
+ local EXPOSED_NAME=dokku.postgres.pg.ambassador
+ local PORT_FILE=/var/lib/dokku/services/postgres/pg/PORT
+ [[ true == \t\r\u\e ]]
+ [[ ! -f /var/lib/dokku/services/postgres/pg/PORT ]]
+ local 'GREP_NAME=^/dokku.postgres.pg.ambassador$'
++ docker ps -f 'name=^/dokku.postgres.pg.ambassador$' --format '{{.Names}}'
+ local CONTAINER_NAME=
+ [[ -z '' ]]
+ [[ true == \t\r\u\e ]]
+ dokku_log_info1 'Service pg unexposed'
+ declare 'desc=log info1 formatter'
+ echo '-----> Service pg unexposed'
-----> Service pg unexposed
+ return
+ rm -rf /var/lib/dokku/services/postgres/pg/PORT
+ implemented=1
+ [[ 1 -eq 0 ]]
+ [[ 1 -eq 0 ]]

```
### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
-----> uname: Linux justa-venda-api 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:            985         339         175          14         469         488
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           19.03.12
        API version:       1.40
        Go version:        go1.13.10
        Git commit:        48a66213fe
        Built:             Mon Jun 22 15:45:36 2020
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          19.03.12
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.10
         Git commit:       48a66213fe
         Built:            Mon Jun 22 15:44:07 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info:
       Client:
        Debug Mode: true

       Server:
        Containers: 4
         Running: 2
         Paused: 0
         Stopped: 2
        Images: 16
        Server Version: 19.03.12
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-52-generic
        Operating System: Ubuntu 18.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 985.5MiB
        Name: justa-venda-api
        ID: WXWM:WDEY:HGZ2:V6GN:B3O2:3RPR:32FH:URP7:AYZ6:LC6L:GEKP:HM4T
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> sigil version: 0.6.0
-----> herokuish version:
Unable to find image 'gliderlabs/herokuish:latest' locally
latest: Pulling from gliderlabs/herokuish
5bed26d33875: Pulling fs layer
f11b29a9c730: Pulling fs layer
930bda195c84: Pulling fs layer
78bf9a5ad49e: Pulling fs layer
5ca853acd559: Pulling fs layer
b8cfb59338be: Pulling fs layer
ebe2379f9a92: Pulling fs layer
3d51acf20b0d: Pulling fs layer
ed356191ca54: Pulling fs layer
cdf55d94c1d9: Pulling fs layer
f317c80ad605: Pulling fs layer
36e537329f4c: Pulling fs layer
3219a255d7d5: Pulling fs layer
78bf9a5ad49e: Waiting
5ca853acd559: Waiting
b8cfb59338be: Waiting
ebe2379f9a92: Waiting
3d51acf20b0d: Waiting
ed356191ca54: Waiting
cdf55d94c1d9: Waiting
f317c80ad605: Waiting
36e537329f4c: Waiting
3219a255d7d5: Waiting
930bda195c84: Verifying Checksum
930bda195c84: Download complete
f11b29a9c730: Verifying Checksum
f11b29a9c730: Download complete
5bed26d33875: Verifying Checksum
5bed26d33875: Download complete
78bf9a5ad49e: Verifying Checksum
78bf9a5ad49e: Download complete
5ca853acd559: Verifying Checksum
5ca853acd559: Download complete
ebe2379f9a92: Verifying Checksum
ebe2379f9a92: Download complete
b8cfb59338be: Verifying Checksum
b8cfb59338be: Download complete
ed356191ca54: Verifying Checksum
ed356191ca54: Download complete
cdf55d94c1d9: Verifying Checksum
cdf55d94c1d9: Download complete
f317c80ad605: Verifying Checksum
f317c80ad605: Download complete
36e537329f4c: Verifying Checksum
36e537329f4c: Download complete
3219a255d7d5: Verifying Checksum
3219a255d7d5: Download complete
3d51acf20b0d: Verifying Checksum
3d51acf20b0d: Download complete
5bed26d33875: Pull complete
f11b29a9c730: Pull complete
930bda195c84: Pull complete
78bf9a5ad49e: Pull complete
5ca853acd559: Pull complete
b8cfb59338be: Pull complete
ebe2379f9a92: Pull complete
3d51acf20b0d: Pull complete
ed356191ca54: Pull complete
cdf55d94c1d9: Pull complete
f317c80ad605: Pull complete
36e537329f4c: Pull complete
3219a255d7d5: Pull complete
Digest: sha256:a567b4af19278f83cff11a58560061829b25e9bcf604b05c4af2ecc702d43c07
Status: Downloaded newer image for gliderlabs/herokuish:latest
       herokuish: 0.5.13
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v171
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v169
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v174
         heroku-buildpack-go        v142
         buildpack-nginx            v13
-----> dokku version: dokku version 0.21.4
-----> dokku plugins:
       plugn: 0.5.0
         00_dokku-standard    0.21.4 enabled    dokku core standard plugin
         20_events            0.21.4 enabled    dokku core events logging plugin
         app-json             0.21.4 enabled    dokku core app-json plugin
         apps                 0.21.4 enabled    dokku core apps plugin
         builder-dockerfile   0.21.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.21.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.21.4 enabled    dokku core buildpacks plugin
         certs                0.21.4 enabled    dokku core certificate management plugin
         checks               0.21.4 enabled    dokku core checks plugin
         common               0.21.4 enabled    dokku core common plugin
         config               0.21.4 enabled    dokku core config plugin
         docker-direct        1.0.0 enabled    dokku plugin to issue docker commands directly
         docker-options       0.21.4 enabled    dokku core docker-options plugin
         domains              0.21.4 enabled    dokku core domains plugin
         enter                0.21.4 enabled    dokku core enter plugin
         git                  0.21.4 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.21.4 enabled    dokku core logs plugin
         network              0.21.4 enabled    dokku core network plugin
         nginx-vhosts         0.21.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.21.4 enabled    dokku core plugin plugin
         postgres             1.11.5 enabled    dokku postgres service plugin
         proxy                0.21.4 enabled    dokku core proxy plugin
         ps                   0.21.4 enabled    dokku core ps plugin
         repo                 0.21.4 enabled    dokku core repo plugin
         resource             0.21.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.21.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.21.4 enabled    dokku core shell plugin
         ssh-keys             0.21.4 enabled    dokku core ssh-keys plugin
         storage              0.21.4 enabled    dokku core storage plugin
         tags                 0.21.4 enabled    dokku core tags plugin
         tar                  0.21.4 enabled    dokku core tar plugin
         trace                0.21.4 enabled    dokku core trace plugin
=====> api app information
       App deploy source:
       App dir:                       /home/dokku/api
       App locked:                    false
=====> api buildpacks information
       Buildpacks list:
CN = api.justavenda.pt
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> api ssl information
       Ssl dir:                       /home/dokku/api/tls
       Ssl enabled:                   true
       Ssl hostnames:                 api.justavenda.pt
       Ssl expires at:                Nov 24 16:24:22 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Aug 26 16:24:22 2020 GMT
       Ssl subject:                   subject=CN = api.justavenda.pt
       Ssl verified:                  self signed
=====> api checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> api docker options information
       Docker options build:          --link dokku.postgres.pg:dokku-postgres-pg
       Docker options deploy:         --link dokku.postgres.pg:dokku-postgres-pg --restart=on-failure:10
       Docker options run:            --link dokku.postgres.pg:dokku-postgres-pg
=====> api domains information
       Domains app enabled:           true
       Domains app vhosts:            api.justavenda.pt
       Domains global enabled:        true
       Domains global vhosts:         justavenda.pt
=====> api git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:
       Git last updated at:
=====> api network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.4:3006
=====> api nginx information
       Nginx access log path:         /var/log/nginx/api-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx error log path:          /var/log/nginx/api-error.log
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1601574880
=====> api proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:3006 https:443:3006
       Proxy type:                    nginx
=====> api ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: 5efdf67b3570)
=====> api scheduler-docker-local information
       Scheduler docker local disable chown:
=====> api storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- App container inspect output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
This might have been a temporary bug. I'm unable to reproduce now:

```
root@dokku:~# dokku postgres:create pg
       Waiting for container to be ready
       Creating container database
       Securing connection to database
=====> Postgres container created: pg
=====> pg postgres service information
       Config dir:          /var/lib/dokku/services/postgres/pg/data
       Config options:
       Data dir:            /var/lib/dokku/services/postgres/pg/data
       Dsn:                 postgres://postgres:b5fd8582b613db63e37ccf0fdfb59c7f@dokku-postgres-pg:5432/pg
       Exposed ports:       -
       Id:                  37db5387c79379b4cd00f7f63c84f1c162b63d31ceaa8b55802591bbbb966b2f
       Internal ip:         172.17.0.7
       Initial network:
       Links:               -
       Post create network:
       Post start network:
       Service root:        /var/lib/dokku/services/postgres/pg
       Status:              running
       Version:             postgres:14.5
root@dokku:~# dokku postgres:expose pg 5432
-----> Service pg exposed on port(s) [container->host]: 5432->5432
root@dokku:~# dokku postgres:unexpose pg
-----> Service pg unexposed
root@dokku:~# dokku postgres:expose pg 5432
-----> Service pg exposed on port(s) [container->host]: 5432->5432
```
