### ISSUE TITLE
Database configuration - command line arguments

### ISSUE THREAD

**Issue by diegoponciano** [dokku/dokku-redis#167]
## Description of problem

The postgres docker image allows us to create and run a containers passing configurations thru command line arguments.
Example commands:

```
docker run -d --name my-pg postgres -c "shared_preload_libraries='pg_stat_statements'"
docker run -d --name some-postgres -e postgres -c shared_buffers=256MB -c max_connections=200
```
Can we do that on using this plugin? Instead of editing `postgresql.conf` directly.

**Comment by josegonzalez** [comment]
This should be completed as of https://github.com/dokku/dokku-redis/commit/720ddea579a069ff55e89e66dd8c6ebfb0303b24, which will be released in 1.16.x of this plugin.
