### ISSUE TITLE
logs with -t are not working properly ❓ 

### ISSUE THREAD

**Issue by ygorpinto** [dokku/dokku-redis#172]
When I try to view the logs using -t (tail) it just ignores the command and logs information from the start of the application.
Is it normal?

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by ygorpinto** [comment]
@josegonzalez Sorry!
**How reproducible**
Steps to Reproduce
1 - just type **dokku redis:logs app_name -t 100**
2 - i just wanna know that the "-t" works on dokku redis, giving me just 100 lines in the log?

**Comment by josegonzalez** [comment]
That executes a command like:

```
docker logs --tail 10 --follow c351a09030b30ab765677649173ada947c1f3817095be5d3cd2823a8278548c4
```

Which is the correct command (you can verify this by checking the command output after running `--trace`).

It's possible that you have a buggy version, but since you didn't add the dokku report output we asked for, I can't debug.

Hope the above helps.
