### ISSUE TITLE
Error on `redis:link`: Could not get container for dokku.postgres.redis

### ISSUE THREAD

**Issue by johnfraney** [dokku/dokku-redis#20]
I may be missing a configuration step, but after creating a redis container (`redis`) and trying to link it to an application via `redis:link`, I get the following error, where `my-app` is a Django app linked to a `dokku-postgres` PostgreSQL container:

```
root@server:~# dokku redis:link redis my-app
-----> Restarting app my-app
-----> Releasing hci-tool (dokku/my-app:latest)...
-----> Deploying hci-tool (dokku/my-app:latest)...
-----> DOKKU_SCALE file found
=====> web=1
cat: /var/lib/dokku/services/redis/redis/PASSWORD: No such file or directory
Error response from daemon: Could not get container for dokku.postgres.redis
```

After adding that `PASSWORD` manually, I get the following error instead:

```
root@server:/var/lib/dokku/services/redis/redis# dokku redis:link redis my-app
-----> Restarting app my-app
-----> Releasing my-app (dokku/my-app:latest)...
-----> Deploying my-app (dokku/my-app:latest)...
-----> DOKKU_SCALE file found
=====> web=1
invalid value "--link" for flag --env: poorly formatted environment: variable '--link' is not a valid environment variable
See 'docker run --help'.
```

Docker: 1.8.2
Dokku: 0.4.0
Ubuntu: 14.04.3

**Comment by josegonzalez** [comment]
That is odd, we don't use a `PASSWORD` file in `dokku-redis`. Can you remove that file and do the following:

```
dokku redis:unlink redis my-app
DOKKU_TRACE dokku redis:link redis my-app
```

And gist the logs? As well, what other plugins are you using?

**Comment by johnfraney** [comment]
I'll have to change my scrollback settings to see the whole output, but here's [a gist with the majority of the output from that command](https://gist.github.com/johnfraney/d0b85c272d744206e7dd).

I just updated `dokku`. I've got the `dokku-postgres` plugin installed, but that's the only one that's active apart from `dokku-redis`, I believe

**Comment by josegonzalez** [comment]
@Flink Do you think that maybe the two `service_url` definitions are not being called properly? Looks like the `service_url` command for postgres is being called here for the redis app.

**Comment by josegonzalez** [comment]
@johnfraney can you do the following for me? In the `postgres` and `redis` plugins, you will have a `config` file. Can you swap out their contents for the following and then retry the unlink/link and paste the output logs?

---

*postgres/config*

```shell
#!/usr/bin/env bash
export POSTGRES_IMAGE=${POSTGRES_IMAGE:="postgres"}
export POSTGRES_IMAGE_VERSION=${POSTGRES_IMAGE_VERSION:="9.4.4"}
export POSTGRES_ROOT=${POSTGRES_ROOT:="/var/lib/dokku/services/postgres"}

export PLUGIN_COMMAND_PREFIX="postgres"
export PLUGIN_DATA_ROOT=$POSTGRES_ROOT
export PLUGIN_DATASTORE_PORTS=(5432)
export PLUGIN_DEFAULT_ALIAS="DATABASE"
export PLUGIN_IMAGE=$POSTGRES_IMAGE
export PLUGIN_IMAGE_VERSION=$POSTGRES_IMAGE_VERSION
export PLUGIN_SCHEME="postgres"
export PLUGIN_SERVICE="Postgres"
```

---

*redis/config*

```shell
#!/usr/bin/env bash
export REDIS_IMAGE=${REDIS_IMAGE:="redis"}
export REDIS_IMAGE_VERSION=${REDIS_IMAGE_VERSION:="3.0.4"}
export REDIS_ROOT=${REDIS_ROOT:="/var/lib/dokku/services/redis"}

export PLUGIN_COMMAND_PREFIX="redis"
export PLUGIN_DATA_ROOT=$REDIS_ROOT
export PLUGIN_DATASTORE_PORTS=(6379)
export PLUGIN_DEFAULT_ALIAS="REDIS"
export PLUGIN_IMAGE=$REDIS_IMAGE
export PLUGIN_IMAGE_VERSION=$REDIS_IMAGE_VERSION
export PLUGIN_SCHEME="redis"
export PLUGIN_SERVICE="Redis"
```

**Comment by johnfraney** [comment]
@josegonzalez Changing those files did the trick. [Here's the `DOKKU_TRACE` output](https://gist.github.com/johnfraney/e09e97328543b645b765)

**Comment by josegonzalez** [comment]
Awesome, sounds like a partial bug in the official datastores. I'll get that fixed up, thanks for hanging in there with the bug reporting :)

**Comment by johnfraney** [comment]
Happy to help! Thanks for dokku, it's awesome! I'm really happy to see these official plugins, now too.

**Comment by josegonzalez** [comment]
And it's been fixed in all official datastores. Thanks again!

**Comment by sjayesh** [comment]
@josegonzalez I am getting following error when running git push dokku master

remote: docker: Error response from daemon: could not get container for dokku.postgres.db: No such container: dokku.postgres.db

Please help me with this.

**Comment by josegonzalez** [comment]
@sjayesh please file a brand new issue (in the postgres repo) with all the info we ask for.
