### ISSUE TITLE
How can I upgrade my redis version? I'm stuck at 5.0.7

### ISSUE THREAD

**Issue by helphop** [dokku/dokku-redis#219]
### I tried: dokku redis:upgrade gouldupdate3_redis
result: Service gouldupdate3_redis already running redis:5.0.7

How then can I upgrade to redis 7.0.12?

I have also attempted to upgrade the version of the dokku-redis plugin but get the following error:

dokku plugin:update redis
fatal: detected dubious ownership in repository at '/var/lib/dokku/plugins/available/redis'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/lib/dokku/plugins/available/redis
/tmp/bashenv.474884758: line 232: ./.plugin_committish: No such file or directory
Plugin pinned to 
-----> Priming bash-completion cache

**Comment by josegonzalez** [comment]
What version of dokku are you running?

**Comment by helphop** [comment]
Dokku version 0.21.4

**Comment by josegonzalez** [comment]
You should upgrade dokku and it's dependencies - that will fix the plugin update issues. If you jump on our discord or slack (links are in our docs) we can help out with that :)

**Comment by helphop** [comment]
He @josegonzalez I can't seem to locate the discord or slack.  When you say docs you mean the ReadMe?

**Comment by josegonzalez** [comment]
dokku.com is our docs site. There should be a doc on "where to get help" there.
