### ISSUE TITLE
Missing environment variables?

### ISSUE THREAD

**Issue by johnfraney** [dokku/dokku-redis#22]
After successfully linking a redis container to my app (`dokku redis:link redis my-app`), the environment variables mentioned in the README do not appear to be added to my app (not in `dokku:config my-app` or in my app's `.env` file). (I noticed that `dokku-postgres` also didn't set the environment variables.)

Is there an extra configuration step I'm missing? Running `dokku redis:info redis` returns:
```
DSN: redis://172.17.1.48:6379/0
```
Docker: 1.8.2
Dokku: 0.4.0

**Comment by sekjun9878** [comment]
I belive that the connection environmental variables are by Docker's linking system itself, so they are set at runtime - not in any configuration file. Have you tried to actually access the environment variable from the application itself?

**Comment by johnfraney** [comment]
Ah, I missed that in the README. Would it be possible to show these in `dokku config my-app`, or are they visible elsewhere?

**Comment by Flink** [comment]
You can view all env vars by using the `env` command inside the container (via `dokku run` for instance).
I’m currently working on a solution to use `config` to manage those vars but I can’t promise anything.

**Comment by johnfraney** [comment]
@Flink Thanks for the clarification!
