### ISSUE TITLE
Redis plugin on Dokku with K3S scheduler

### ISSUE THREAD

**Issue by dmitryrechkin** [dokku/dokku-redis#247]
## Description of problem
I am using Dokku with the k3s scheduler, so my application runs as a pod on k3s. I have added the Redis plugin and linked it to my application.

Here  are the details:
------
> dokku redis:info wordpress-nginx
=====> project redis service information
       Config dir:          /var/lib/dokku/services/redis/projectconfig
       Config options:                               
       Data dir:            /var/lib/dokku/services/redis/project/data
       Dsn:                 redis://:XXXXX@dokku-redis-project:6379
       Exposed ports:       -                        
       Id:                  XXXXXXX
       Internal ip:         172.17.0.2               
       Initial network:                              
       Links:               wordpress-nginx          
       Post create network:                          
       Post start network:                           
       Service root:        /var/lib/dokku/services/redis/project
       Status:              running                  
       Version:             redis:7.2.5              
       
> dokku redis:links
project
-----
As far as I understand, the Redis service runs in Docker instead of k3s, and the pod cannot connect to it.

I cannot even ping this IP from the pod:
> /var/www/html $ ping 172.17.0.2
PING 172.17.0.2 (172.17.0.2): 56 data bytes

However, I can ping it from the host:
> dokku@dokku-server-1:~$ sudo ping 172.17.0.2
PING 172.17.0.2 (172.17.0.2) 56(84) bytes of data.
64 bytes from 172.17.0.2: icmp_seq=1 ttl=64 time=0.067 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=64 time=0.043 ms

Questions
	1.	Is there a way to make the Redis service accessible from the k3s pod?
	2.	Is there a way to run the Redis service on k3s instead of Docker?

**Comment by josegonzalez** [comment]
None of the datastore plugins support alternative schedulers. They only work on docker-local.

For kubernetes/k3s support, I would suggest looking into the official helm chart provided by the datastore provider in question.

**Comment by dmitryrechkin** [comment]
Alright, that is as much as I’ve figured out so far. Hopefully, it will be improved one day. In the meantime, in case anyone else has the same questions I did, I’ve created a repo with instructions on how to get Redis working with Dokku on K3S.

https://github.com/dmitryrechkin/docker-redis
