### ISSUE TITLE
Redis daemon configurations?

### ISSUE THREAD

**Issue by sekjun9878** [dokku/dokku-redis#26]
Hello,

Is there any way to configure the Redis daemon's configuration file?

https://github.com/sekjun9878/dokku-redis-plugin/issues/33

Or should I implement one?

**Comment by josegonzalez** [comment]
The `/usr/local/etc/redis`directory is mounted into `/var/lib/dokku/services/redis/SERVICE_NAME/config`. You can stop your container, modify the config, and start it again.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response.

**Comment by dhruvio** [comment]
I have added a `redis.conf` to `/var/lib/dokku/services/redis/$SERVICE_NAME/config`, but when I look at the service's redis logs after restarting, it has not detected a config file. Thoughts @josegonzalez ?
