### ISSUE TITLE
Document how to configure Redis

### ISSUE THREAD

**Issue by blopker** [dokku/dokku-redis#30]
Hey, this plugin is working great, but I need to set up Redis as an LRU cache.

Is there an easy way to tell the plugin what config to use? Maybe through a environment variable?

Also the plugin doesn't seem to pull down the latest image on install. `docker pull redis` fixes that though.

**Comment by blopker** [comment]
Shoot, I just saw #26. That will work, but it would still be nice to set the path to a config through an env variable.

**Comment by josegonzalez** [comment]
@blopker what do you mean by the config path?

**Comment by blopker** [comment]
Ah, sorry. The Redis image says you can supply your own `redis.conf` file with something like: 
```
$ docker run -v /myredis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name myredis redis redis-server /usr/local/etc/redis/redis.conf
Where /myredis/conf/ is a local directory containing your redis.conf file. Using this method means that there is no need for you to have a Dockerfile for your redis container.
```
I haven't looked at how docker is actually run, but being able to set `redis.conf` from a file located on the host machine would be nice. Something like:
```
$ docker run -v $REDIS_IMAGE_CONF:/usr/local/etc/redis/redis.conf --name myredis redis redis-server /usr/local/etc/redis/redis.conf
```

**Comment by josegonzalez** [comment]
We simply mount that directory in our own config dir. While allowing a user to specify that file on their own seems nice, it complicates stuff like backups etc. (where is my redis.conf omg). I think we're going to leave it where it is, since you can already configure it well enough from there.

**Comment by blopker** [comment]
Fair enough. Since there were two issues about this already, would you mind putting conf instructions in the readme?

**Comment by josegonzalez** [comment]
Reopening issue so this sort of stuff can be documented everywhere.

**Comment by blopker** [comment]
Fixed the title for you :)

**Comment by josegonzalez** [comment]
<3

**Comment by blopker** [comment]
Did that commit add to the docs or just bump the version of Redis?

**Comment by josegonzalez** [comment]
Sorry, it just bumped redis version. I'll take a look at docs soon.

**Comment by dhruvio** [comment]
Just saw this — I've already commented on #26, but I will reiterate my question here:

I have added a `redis.conf` to `/var/lib/dokku/services/redis/$SERVICE_NAME/config`, but when I look at the service's redis logs after restarting, it has not detected a config file. Thoughts?

Looking at docker's official redis image [documentation](https://hub.docker.com/_/redis/), you need to specify the conf file if it is `/usr/local/etc/redis/redis.conf` — it isn't the default. I believe the default is `/etc/redis.conf`. Looking at the `commands` file in the repo, it looks `redis-server` is run without specifying any config file?

**Comment by dhruvio** [comment]
Here's the output from `docker inspect $CONTAINER_ID`, where contianer ID is the output of `/var/lib/dokku/services/redis/$SERVICE_NAME/ID`:

https://gist.github.com/dhruvio/63cf43b1eb222fa75879

As you can see, the `cmd` property is just `redis-server` without specifying the custom `redis.conf` file.

**Comment by josegonzalez** [comment]
Can you mount a single file? If not, I'm not sure what the best fix is here if they default to using `/etc/redis.conf`. I assume using that will break the image.

**Comment by dhruvio** [comment]
Yeah, I think the solution will be to, by default, include the standard redis.conf file in the `/var/lib/dokku/services/redis/$SERVICE_NAME/config` directory. Then, instead of running the vanilla docker redis container as-is, we run a custom Dockerfile that pulls from the official redis image, except the executing command is `redis-server /usr/local/etc/redis/redis.conf` instead of just `redis-server`. Does that make sense?

**Comment by dhruvio** [comment]
I have found a simpler solution, and created a [pull request](https://github.com/dokku/dokku-redis/pull/39). I have not tested this locally, as I do not have a dev environment set up. Let me know if you think this is a good solution.

**Comment by josegonzalez** [comment]
Calling `dokku redis:info SERVICE` will now output the config and data directories for a given service.
