### ISSUE TITLE
Clustering?

### ISSUE THREAD

**Issue by KayoticSully** [dokku/dokku-redis#41]
Is there a known way to cluster redis servers on dokku? 

Would this require a different plugin or could this one be modified to work in that way?

**Comment by josegonzalez** [comment]
How would you cluster redis servers outside of dokku?

**Comment by KayoticSully** [comment]
Normally you would run the cluster creation tool using redistrib.rb. From the repository. You can probably do it by hand too but all the servers need to have connectivity to each other and to the clients.  I just have not been able to figure out a "good way" to do this with docker that works well with dokku.  Can I link service containers together?  And temporarily pass the ports through to the host for initial configuration of the cluster?  

It may be easier to cluster redis together within a docker image... If I go that route I'll probably need to create a new redis plugin for dokku.  I was just hoping to avoid having to do that.

**Comment by josegonzalez** [comment]
I think clustering is outside the scope of this plugin. If you want a more bullet-proof redis solution, I recommend that you lookin into using ElastiCache or some other redis provider.
