### ISSUE TITLE
How to configure the redis plugin to run a custom docker image for the install

### ISSUE THREAD

**Issue by erikschlegel** [dokku/dokku-redis#43]
I have a custom image thats using the redis release candidate version 3.2, which supports geospatial indexes. How do I configure the redis plugin to use a different image not included in the https://hub.docker.com/r/library/redis/tags/ ? Tried changing the REDIS_IMAGE_VERSION and REDIS_IMAGE vars but I received a Redis image x:y not found'.

All the best,

Erik

**Comment by josegonzalez** [comment]
What did you set those values to, and what was *the exact* message?

You will also need to pull that image down.

**Comment by erikschlegel** [comment]
thanks for the response. I'm setting the 2 variables to the following. Just an FYI, I'm still learning the ropes to both redis and dokku. 

export REDIS_IMAGE="erikschlegel/redis-rc"
export REDIS_IMAGE_VERSION="3.2.0"

When I try and create a new redis service I receive the following statement.

dokku redis:create guidedogs-cache-service

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 45390  100 45390    0     0   208k      0 --:--:-- --:--:-- --:--:--  209k
-----> Starting container
       Waiting for container to be ready

I'm not able to pass this message. 

Appreciate your help.

All the best,

Erik

**Comment by josegonzalez** [comment]
Does your image work in the same fashion as the official redis image? If not, then the waiting section may fail.

**Comment by erikschlegel** [comment]
It seems to start with no issues. I included in the output below. 

dogmaster@DokkuVM:~/docker$ sudo docker run -t -i erikschlegel/redis-rc:3.2.0
1:C 24 Mar 22:44:40.773 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.1.103 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 24 Mar 22:44:40.777 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 24 Mar 22:44:40.777 # Server started, Redis version 3.1.103
1:M 24 Mar 22:44:40.777 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 24 Mar 22:44:40.777 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 24 Mar 22:44:40.777 * The server is now ready to accept connections on port 6379

**Comment by josegonzalez** [comment]
Did you ever get this sorted?
