### ISSUE TITLE
Please do not append /0 in REDIS_URL

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku-redis#50]
Same arguments as in https://github.com/sekjun9878/dokku-redis-plugin/issues/25 :

Hi,

On heroku, REDIS_URL (say Open Redis) is never defined with the database number at the end (/0). This allows one to define sub-areas by just appending /N to REDIS_URL. Therefore, I would like to suggest that you no longer do this:

KEY="REDIS_URL"
VALUE="redis://redis:6379/0"

but instead do this:

KEY="REDIS_URL"
VALUE="redis://redis:6379"

So that apps can be run on heroku or on dokku with no changes regarding REDIS.

Thanks for listening.

**Comment by josegonzalez** [comment]
You can change your database in code. What stops you from doing that?

**Comment by sglebs** [comment]
I have the following environment variables:

```
CELERY_BROKER_URL=$REDIS_URL/13
GENERICCOUNTERS_REDIS=$REDIS_URL/11
PROFILE_REDIS_CACHE_URL=$REDIS_URL/1
PUSHPROFILE_REDIS_CACHE_URL=$REDIS_URL/2
```

This code works fine under Heroku and with the Redis plugin from https://github.com/sekjun9878/dokku-redis-plugin/issues/25

You suggest I write custom code to work with this dokku plugin in an ad-hoc way. I humbly suggest that dokku should be fully compatible with Heroku, which seems to be the trend of the dokku project. To be truly fully compatible, /0 is the most natural and clean choice.

My 2 cents.

Obviously if you prefer to keep it as is I can use https://github.com/sekjun9878/dokku-redis-plugin/issues/25 instead, no problem. But I'd rather use the official one (yours) without extra hacks.

**Comment by josegonzalez** [comment]
Mind making a PR for this?

**Comment by sglebs** [comment]
sure: https://github.com/dokku/dokku-redis/pull/51
