### ISSUE TITLE
can't link or promote 2 redis into same app

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku-redis#52]
I have 2 micro services / REST apps  A and B, each with a REDIS (Ra and Rb) for caching. But it turns out that, beyond B having Rb, it also needs access to Ra  (the 2 apps interop via Python Celery using the shared Redis Ra/14). Unfortunately I can't redis:promote or redis:link Ra into B because promote and link assume the env var is REDIS_URL but B already has its own REDIS_URL, which I do not want to lose/override.

How about allowing redis:promote or redis:link callers to pass an optional extra parameter, which is the env var name to use (REDIS_URL is just a default when nothing is passed)

I am scripting the setup (https://github.com/sglebs/ndeploy) so I am interested in avoiding human intervention.

Thanks for listening!

**Comment by josegonzalez** [comment]
@Flink could this be done using aliasing somehow? Pretty sure you worked on this functionality.

**Comment by sglebs** [comment]
I see that when I redis:link you automatically promote as REDIS_URL. If I could pass the env var name to redis:link, it would be awesome, as I could give semantically meaningful names. As a second option, also ok, would be for you to assume env var name "<service-name>_URL". So, if I named my redis service "redis-messenger-server", you could use env var name REDIS_MESSENGER_SERVER_URL. Perhaps this second approach is easier to implement? And then, redis:promote would promote is as REDIS_URL.

**Comment by josegonzalez** [comment]
Well if we link, we *should* be using an alias (`DOKKU_BLUE` etc.).

**Comment by sglebs** [comment]
How about using as an alias  "[service-name]_URL"? It would make things really easy to automate via scripts. As is, it is generated/"random".

**Comment by josegonzalez** [comment]
We're simply doing what heroku does here. Ideally you can provide an alias, but atm we just "default" to a given alias when you're already linked.

**Comment by josegonzalez** [comment]
Possible cli ui:

```
dokku redis:link SERVICE APP --alias ALIAS
```

**Comment by josegonzalez** [comment]
Closing in favor of a rather large rfc here: dokku/dokku-redis/issues/64
