### ISSUE TITLE
Allow instance creation without password

### ISSUE THREAD

**Issue by ohardy** [dokku/dokku-redis#68]
I have some services like gitlab who doesn't support redis password actually.

**Comment by josegonzalez** [comment]
Not for nothing, but file a bug with those services? Seems silly that they wouldn't support it, since basically any reasonable redis library has auth support.

**Comment by josegonzalez** [comment]
Aside, it would be more difficult to conditionally set passwords for just this one service, since we don't have similar functionality elsewhere. If you're willing to do the work though, I'd be happy to see about merging it (and replicating elsewhere).

**Comment by chrisnicola** [comment]
Gitlab is just using Sidekiq. It should support a password just fine.

**Comment by josegonzalez** [comment]
I'm going to close this. I'd hope now that Redis has had auth for years that most/all tools now support auth.

**Comment by pawelad** [comment]
FWIW, I found one: https://monetr.app/documentation/configure/redis/

> monetr does not support credentials or TLS for this cache server at this time. Sensitive information is never cached on this server and the use of the cache is purely for performance.
