### ISSUE TITLE
DOCKER_OPTIONS_DEPLOY permission denied

### ISSUE THREAD

**Issue by PAStheLoD** [dokku/dokku-redis#78]
Hello,

Thanks for this plugin, seems very straightforward to use, however, I've encountered a minor error.

After creating the DB I tried to link it:
`dokku redis:link db-name app-name` and got an error: `/var/lib/dokku/plugins/available/docker-options/functions: line 89: /home/dokku/app-name/DOCKER_OPTIONS_DEPLOY: Permission denied`

After `chmod o+w /home/dokku/app-name/DOCKER_OPTIONS_DEPLOY` the linking succeeded.

Thanks!

**Comment by josegonzalez** [comment]
Seems like you may have screwed permissions on your application directories. I'd check to verify that everything is owned by the `dokku:dokku` user and group.
