### ISSUE TITLE
No such file or directory on empty backup

### ISSUE THREAD

**Issue by ksmandersen** [dokku/dokku-redis#80]
I set up a new redis empty instance and set the aws credentials. The calling backup gives the following error:
```bash
root@speakerdex:~# dokku redis:backup speakerdex-sessions speakerdex-redis-backups
cat: /data/dump.rdb: No such file or directory
```

**Comment by josegonzalez** [comment]
Can you gist the output of:

```
dokku --trace redis:backup speakerdex-sessions speakerdex-redis-backups
```

**Comment by ksmandersen** [comment]
@josegonzalez Here's the output:

https://gist.github.com/ksmandersen/1e092c0358575281976ba61e2233d262

**Comment by josegonzalez** [comment]
Looks like this was implemented by @flink [here](https://github.com/dokku/dokku-redis/pull/8). I think maybe the dump isn't being saved to that file?

If you `dokku redis:enter` and run the following, what happens?

```shell
echo "SAVE" | redis-cli
```

**Comment by ksmandersen** [comment]
I get this message:
```
(error) NOAUTH Authentication required.
```

**Comment by josegonzalez** [comment]
Please update your plugin installation, you are running an older version.

**Comment by ksmandersen** [comment]
That sounds unlikely since I installed the plugin yesterday. I ran dokku plugin:update redis.
``dokku plugin`` tells me that I am running 1.0.0. The problem still persists

**Comment by josegonzalez** [comment]
Can you do:

```
dokku --trace redis:enter SERVICE
```

**Comment by ksmandersen** [comment]
Output here:
https://gist.github.com/ksmandersen/4e521ae4d4b2297b7532bf2c82119a6c

**Comment by josegonzalez** [comment]
Ah the `redis-cli` needs the password to authenticate. You can get that from `dokku redis:info SERVICE`.

**Comment by ksmandersen** [comment]
So after doing ``dokku redis:enter`` and then ``echo "SAVE" | redis-cli -a "thepassword"`` the backup command works fine. Is this the intended behaviour?

**Comment by josegonzalez** [comment]
Okay so I think we need to include the password in the redis:export command. Let me take a look at it now.

**Comment by josegonzalez** [comment]
Try updating and using the export command now.
