### ISSUE TITLE
Backup cron breaks if invalid service name

### ISSUE THREAD

**Issue by MikeSchroll** [dokku/dokku-redis#81]
When a backup is created, it crafts a file in /etc/cron.d/ based on the filename of the service.

Unfortunately cron does not support certain characters in files listed there.

Can we replace any invalid characters with underscores when creating this file, so the cron job created still works properly?

Ref: https://serverfault.com/questions/425232/adding-file-to-etc-cron-d-doesnt-make-it-run-ubuntu-10-04#614832

**Comment by josegonzalez** [comment]
Sure, can you provide a test-case?

**Comment by josegonzalez** [comment]
Actually we should just disable the creation of invalid service names. Probably only allow alphanumeric characters - which will break users with invalid services.
