### ISSUE TITLE
Installing a custom elasticsearch image --> replace "docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"?

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-redis#83]
_From @dmr on February 11, 2017 5:56_

I'm trying to build my own elasticsearch image which requires a specific version and plugins and the plugin always executes 

```docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"```

I think it would be more generic to only have one variable `ELASTICSEARCH_IMAGE="elasticsearch:2.3.3` which would allow me to replace this with a custom url that I like.

Maybe I understood docker pull wrong but is there a reason for the second variable?

_Copied from original issue: dokku/dokku-elasticsearch#50_

**Comment by josegonzalez** [comment]
We pull an image and a version of that image. You can do `ELASTICSEARCH_IMAGE=dmr/yolo` and `ELASTICSEARCH_IMAGE_VERSION=latest` if you wanted. They are separate because they are separate, nothing more.

**Comment by josegonzalez** [comment]
_From @dmr on February 11, 2017 6:48_

I was hoping that I could use a git repository as a source because I use private repositories. I try to use a url as a image but that does not work yet

(http://stackoverflow.com/questions/26753030/how-to-build-docker-image-from-github-repository)

**Comment by dmr** [comment]
I solved this "issue" by registering an image at the dockerhub, I think this is ok for now IMO

**Comment by khakulov** [comment]
```
export ELASTICSEARCH_IMAGE="docker.elastic.co/elasticsearch/elasticsearch"
export ELASTICSEARCH_IMAGE_VERSION="6.0.1"
dokku elasticsearch:create myinstance
```

**Comment by josegonzalez** [comment]
Closing as the correct alternative is to use a registry. I don't think it makes sense for us to try and detect a git repo vs a regular registry at this time (I can imagine special casing github will lead to people trying to special case other servers).
